version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.1'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2
            ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: 'bitnami/kafka:3.1.2'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    expose:
            - "9092"
    depends_on:
            - zookeeper
    working_dir: /opt/bitnami/kafka
    environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
  mongo:
    container_name: mongo
    ports:
      - "27019:27017"
    build:
      context: ./docker/Mongo
      dockerfile: Dockerfile
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_HOME =/spark
      - PROJECT_HOME =/home/lucia/practica_creativa
    volumes:
      - ./:/home/lucia/practica_creativa
    depends_on:
      - kafka
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./:/home/lucia/practica_creativa
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_HOME =/spark
      - PROJECT_HOME =/home/lucia/practica_creativa
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./:/home/lucia/practica_creativa
    environment:
      - "SPARK_MASTER=spark://spark-master:7077" 
      - SPARK_HOME =/spark
      - PROJECT_HOME =/home/lucia/practica_creativa
  spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: spark-history-server
      depends_on:
        - spark-master
      ports:
        - "18081:18081"
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events
  webserver:
    container_name: webserver
    ports:
      - "5001:5001"
    environment: 
      - SPARK_HOME=/spark
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-history-server
      - mongo
    build:
      context: ./docker/Flask
      dockerfile: Dockerfile